### PR TITLE
Progressively enhanced details

### PR DESCRIPTION
**Pull request by sh0ji**
This is still incomplete, as I'm uncertain about the tests and I've yet to add all the IDs that are necessary. Any help on those fronts would be appreciated!

@clapierre, quite a lot of the features that it implements are identical to the other tests that use `aria-details` + `details` so I've only written tests for the enhancements.

* Reduced motion: a test to verify that the reading system supports the [prefers-reduced-motion](https://drafts.csswg.org/mediaqueries-5/#descdef-media-prefers-reduced-motion) media query.
* Fine pointer: a test to verify that the reading system supports the [pointer](https://drafts.csswg.org/mediaqueries-4/#pointer) media query.
* JavaScript-added alt text: the image's alt text is being added to the `<details>` via JavaScript, so this is being tested. This strikes me as just a test of whether or not JavaScript is enabled, though.

### CODE REVIEW

**Comment by marisademeglio** [comment]
Hi @sh0ji, when you're done adding tests, have a look at the existing ID scheme and the guidelines in README and just copy what's there. There's no magic going on with the IDs, they just have to be unique. Typically, the format has been section-number, e.g. `anno-100` for annotations. We've left the numbers spaced out so that it's easy to insert new tests in between in the future.

**Comment by sh0ji** [comment]
Thanks for resolving the remaining issues, @clapierre!

@marisademeglio, this appears to be done unless there's something I'm missing.

**Comment by sh0ji** [comment]
I lied...there was one little issue that I fixed in 56d0b98.

**Comment by clapierre** [comment]
I just ran the build script so that the latest EPUB in the build directory for this version has these changes as well.

**Comment by sh0ji** [comment]
@clapierre, this should address most of the issues we've discussed over email. Take a look and let me know if it's ready to build (and maybe merge!).

**Comment by sh0ji** [comment]
@clapierre, I see you've added a few things. Was there anything else you needed me to do to get this merged?

**Comment by clapierre** [comment]
@sh0ji No I think we are good, for now, the remaining tasks are for Avneesh to give us brief descriptions for each test so when they pull this into the EPUBTest.org website it can be ingested without compromising their UI.  I will handle adding those descriptions correctly to this.

Thanks Evan

**Pull request merged**
