### PR TITLE
Updated accessibility metadata

### PR DESCRIPTION
**Pull request by clapierre**
Ready for @marisademeglio's review.
In addition to the updated accessibility metadata, I commented out the nav.xhtml from the spine as it wasn't being referenced and caused an EPUBCheck error. 
I also updated the alt text descriptions of two supplemental images as having alt="Figure" is inappropriate.

### CODE REVIEW

**Comment by marisademeglio** [comment]
Ok thanks for the PR. It seems like no tests have changed, is that correct? 

And as mentioned in this issue for the non-visual reading tests, I don't see how the page break metadata is relevant here either. https://github.com/daisy/epub-accessibility-tests/issues/90. 

Also test visual-010 refers to a pagelist but there is none.

**Comment by clapierre** [comment]
good point, I will remove those from the list, was just grabbing what George had.

**Comment by clapierre** [comment]
I was just asked to update the metadata and noticed the issue with the image descriptions so I added that.  No tests were changed.

As for page Lists good question, as this would be part of the reading system, but would mean that we will need to add page breaks and a page list.

@GeorgeKerscher did we want to do this as well here? So it can be tested with increasing the font size in test 010. 

Or should I just remove that text from the introduction of 010
IE:
Change Font Size 
Use the controls available in the application or else in the operating system to change (increase/decrease) the size of the font. The font size change should apply uniformly on all the book content including the Table of Contents, Footnotes, **Page List**, Notes and Bookmarks.

**Comment by GeorgeKerscher** [comment]
Charles, if you think that Reading Systems would make navigation by pages difficult for low vision users, then yes, add the page breaks and page list to test it. However, if you think it is a test everybody would pass if they pass the other tests, then you can leave it out.

**Comment by GeorgeKerscher** [comment]
George will be removing page break markers in my non-visual book as well, and will also remove the page list metadata.

I think this sounds good to go.

**Comment by clapierre** [comment]
@marisademeglio I think we are good to go now. Thanks

**Comment by marisademeglio** [comment]
@clapierre was there a decision not to fix visual-010 ?

**Comment by clapierre** [comment]
No decision made persay, would rather someone who has actually ran this test comment as I have never done this. so I don't know what they did in the past regarding page navigation the test mentions.

**Comment by marisademeglio** [comment]
Ok I will open a new issue about visual-010.

**Pull request merged**
